// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/hl540/my-realworld/internal/biz"
	"github.com/hl540/my-realworld/internal/conf"
	"github.com/hl540/my-realworld/internal/data"
	"github.com/hl540/my-realworld/internal/server"
	"github.com/hl540/my-realworld/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewGormClient(confData, logger)
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userUseCase := biz.NewUserUseCase(confServer, userRepo, logger)
	articleRepo := data.NewArticleRepo(dataData)
	tagRepo := data.NewTagRepo(dataData)
	articleUseCase := biz.NewArticleUseCase(articleRepo, userRepo, tagRepo, logger)
	myRealworldService := service.NewMyRealworldService(userUseCase, articleUseCase)
	grpcServer := server.NewGRPCServer(confServer, myRealworldService, logger)
	httpServer := server.NewHTTPServer(confServer, myRealworldService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
