server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  jwt:
    secretKey: "123456789"
    whitePath:
      - "/api.my_realworld.v1.MyRealworld/Auth" # 鉴权
      - "/api.my_realworld.v1.MyRealworld/Register" # 注册
      - "/api.my_realworld.v1.MyRealworld/GetTags" # 获取tag
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
